ALTER TABLE users ADD COLUMN IF NOT EXISTS ai_query_count INT NOT NULL DEFAULT 0;
ALTER TABLE users ADD COLUMN IF NOT EXISTS last_ai_query_date DATE;
ALTER TABLE users ADD COLUMN IF NOT EXISTS subscription_status VARCHAR(255);
ALTER TABLE users ADD COLUMN IF NOT EXISTS subscription_expires_at BIGINT;
